const phrases = [
    "negativo", 
	"eu não", 
	"você que é", 
	"kid bengala", 
	"ah sim claro",
	"vai toma no glub",
	"eu hein kkk",
	"oxi",
	"assim",
	"tipo assim",
	"tipo",
	"o meu amor",
	"tava demorandooooo",
	"Vitão vai atiçar minha cobra",
	"me mata logo vai",
	"é só por isso mesmo, entendeu?",
	"essas coisas tudo",
	"andar não, vamos de uber",
	"vocês já comeram?",
	"acho que vou pedir um bk",
	"vou comprar monster",
	"vou ligar pro Gio pra saber onde ele tá",
	"oh puta, cade você?",
	"o Kris vai vir",
	"vocês vão pedir comida?",
	"pior que não comi nada antes de vir",
	"vou só tomar um banho e já vou",
	"alguém afim de jogar magica hoje?",
	"Imagina o sal ...",
	"não, pera...",
	"não, não, não... não vou atacar ninguem",
	"tipo assim, vai virar um jogo de comadre",
	"tipo assim, sério...",
	"ta, ta, ta, ta, ta...",
	"eu sei... eu sei... eu sei amore",
	"devidamente",
	"Saudades do sr",
]

export default function GetPhrases() {

    return phrases;
}